image: archlinux
sources:
  - https://git.sr.ht/~tcarrio/git-mirror
  - https://git.sr.ht/~tcarrio/bootstrap-vim
environment:
  PROJECT_DIR: bootstrap-vim
  GIT_TARGET_REPO: git@github.com:tcarrio/bootstrap-vim.git
secrets:
  - 4e983fc2-9d24-43eb-9986-1c18feb2e7b8
tasks:
  - mirror-all: git-mirror/git-mirror.sh $PROJECT_DIR